package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1



/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private Long idbairro;
     private Jurisdicao jurisdicao;
     private String nome;

    public Bairro() {
    }

	
    public Bairro(Jurisdicao jurisdicao) {
        this.jurisdicao = jurisdicao;
    }
    public Bairro(Jurisdicao jurisdicao, String nome) {
       this.jurisdicao = jurisdicao;
       this.nome = nome;
    }
   
    public Long getIdbairro() {
        return this.idbairro;
    }
    
    public void setIdbairro(Long idbairro) {
        this.idbairro = idbairro;
    }
    public Jurisdicao getJurisdicao() {
        return this.jurisdicao;
    }
    
    public void setJurisdicao(Jurisdicao jurisdicao) {
        this.jurisdicao = jurisdicao;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


