package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Long idcategoria;
     private String nome;
     private String cor;
     private Set ordems = new HashSet(0);
     private Set viagems = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nome, String cor, Set ordems, Set viagems) {
       this.nome = nome;
       this.cor = cor;
       this.ordems = ordems;
       this.viagems = viagems;
    }
   
    public Long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Set getOrdems() {
        return this.ordems;
    }
    
    public void setOrdems(Set ordems) {
        this.ordems = ordems;
    }
    public Set getViagems() {
        return this.viagems;
    }
    
    public void setViagems(Set viagems) {
        this.viagems = viagems;
    }




}


