package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Long idcidade;
     private Inspetoria inspetoria;
     private String nome;
     private Set jurisdicaos = new HashSet(0);
     private Set feriados = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public Cidade(Inspetoria inspetoria, String nome, Set jurisdicaos, Set feriados) {
       this.inspetoria = inspetoria;
       this.nome = nome;
       this.jurisdicaos = jurisdicaos;
       this.feriados = feriados;
    }
   
    public Long getIdcidade() {
        return this.idcidade;
    }
    
    public void setIdcidade(Long idcidade) {
        this.idcidade = idcidade;
    }
    public Inspetoria getInspetoria() {
        return this.inspetoria;
    }
    
    public void setInspetoria(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getJurisdicaos() {
        return this.jurisdicaos;
    }
    
    public void setJurisdicaos(Set jurisdicaos) {
        this.jurisdicaos = jurisdicaos;
    }
    public Set getFeriados() {
        return this.feriados;
    }
    
    public void setFeriados(Set feriados) {
        this.feriados = feriados;
    }




}


