package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ferias generated by hbm2java
 */
public class Ferias  implements java.io.Serializable {


     private Long idferias;
     private Fiscal fiscal;
     private Date inicio;
     private Date fim;

    public Ferias() {
    }

	
    public Ferias(Fiscal fiscal) {
        this.fiscal = fiscal;
    }
    public Ferias(Fiscal fiscal, Date inicio, Date fim) {
       this.fiscal = fiscal;
       this.inicio = inicio;
       this.fim = fim;
    }
   
    public Long getIdferias() {
        return this.idferias;
    }
    
    public void setIdferias(Long idferias) {
        this.idferias = idferias;
    }
    public Fiscal getFiscal() {
        return this.fiscal;
    }
    
    public void setFiscal(Fiscal fiscal) {
        this.fiscal = fiscal;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFim() {
        return this.fim;
    }
    
    public void setFim(Date fim) {
        this.fim = fim;
    }




}


