package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Feriado generated by hbm2java
 */
public class Feriado  implements java.io.Serializable {


     private Long idferiado;
     private String nome;
     private Date data;
     private Boolean isFixo;
     private Set cidades = new HashSet(0);

    public Feriado() {
    }

    public Feriado(String nome, Date data, Boolean isFixo, Set cidades) {
       this.nome = nome;
       this.data = data;
       this.isFixo = isFixo;
       this.cidades = cidades;
    }
   
    public Long getIdferiado() {
        return this.idferiado;
    }
    
    public void setIdferiado(Long idferiado) {
        this.idferiado = idferiado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Boolean getIsFixo() {
        return this.isFixo;
    }
    
    public void setIsFixo(Boolean isFixo) {
        this.isFixo = isFixo;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


