package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fiscal generated by hbm2java
 */
public class Fiscal  implements java.io.Serializable {


     private Long idfiscal;
     private Inspetoria inspetoria;
     private String nome;
     private String sobrenome;
     private String sigla;
     private Integer matricula;
     private Boolean isAtivo;
     private Set usuarios = new HashSet(0);
     private Set ordems = new HashSet(0);
     private Set feriases = new HashSet(0);
     private Set viagems = new HashSet(0);

    public Fiscal() {
    }

	
    public Fiscal(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public Fiscal(Inspetoria inspetoria, String nome, String sobrenome, String sigla, Integer matricula, Boolean isAtivo, Set usuarios, Set ordems, Set feriases, Set viagems) {
       this.inspetoria = inspetoria;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.sigla = sigla;
       this.matricula = matricula;
       this.isAtivo = isAtivo;
       this.usuarios = usuarios;
       this.ordems = ordems;
       this.feriases = feriases;
       this.viagems = viagems;
    }
   
    public Long getIdfiscal() {
        return this.idfiscal;
    }
    
    public void setIdfiscal(Long idfiscal) {
        this.idfiscal = idfiscal;
    }
    public Inspetoria getInspetoria() {
        return this.inspetoria;
    }
    
    public void setInspetoria(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getOrdems() {
        return this.ordems;
    }
    
    public void setOrdems(Set ordems) {
        this.ordems = ordems;
    }
    public Set getFeriases() {
        return this.feriases;
    }
    
    public void setFeriases(Set feriases) {
        this.feriases = feriases;
    }
    public Set getViagems() {
        return this.viagems;
    }
    
    public void setViagems(Set viagems) {
        this.viagems = viagems;
    }




}


