package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inspetoria generated by hbm2java
 */
public class Inspetoria  implements java.io.Serializable {


     private Long idinspetoria;
     private String nome;
     private Set fiscals = new HashSet(0);
     private Set rotas = new HashSet(0);
     private Set cidades = new HashSet(0);

    public Inspetoria() {
    }

    public Inspetoria(String nome, Set fiscals, Set rotas, Set cidades) {
       this.nome = nome;
       this.fiscals = fiscals;
       this.rotas = rotas;
       this.cidades = cidades;
    }
   
    public Long getIdinspetoria() {
        return this.idinspetoria;
    }
    
    public void setIdinspetoria(Long idinspetoria) {
        this.idinspetoria = idinspetoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getFiscals() {
        return this.fiscals;
    }
    
    public void setFiscals(Set fiscals) {
        this.fiscals = fiscals;
    }
    public Set getRotas() {
        return this.rotas;
    }
    
    public void setRotas(Set rotas) {
        this.rotas = rotas;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


