package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jurisdicao generated by hbm2java
 */
public class Jurisdicao  implements java.io.Serializable {


     private Long idjurisdicao;
     private Cidade cidade;
     private String nome;
     private Set rotas = new HashSet(0);
     private Set ordems = new HashSet(0);
     private Set bairros = new HashSet(0);

    public Jurisdicao() {
    }

	
    public Jurisdicao(Cidade cidade) {
        this.cidade = cidade;
    }
    public Jurisdicao(Cidade cidade, String nome, Set rotas, Set ordems, Set bairros) {
       this.cidade = cidade;
       this.nome = nome;
       this.rotas = rotas;
       this.ordems = ordems;
       this.bairros = bairros;
    }
   
    public Long getIdjurisdicao() {
        return this.idjurisdicao;
    }
    
    public void setIdjurisdicao(Long idjurisdicao) {
        this.idjurisdicao = idjurisdicao;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getRotas() {
        return this.rotas;
    }
    
    public void setRotas(Set rotas) {
        this.rotas = rotas;
    }
    public Set getOrdems() {
        return this.ordems;
    }
    
    public void setOrdems(Set ordems) {
        this.ordems = ordems;
    }
    public Set getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Set bairros) {
        this.bairros = bairros;
    }




}


