package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rota generated by hbm2java
 */
public class Rota  implements java.io.Serializable {


     private Long idrota;
     private Inspetoria inspetoria;
     private String nome;
     private Integer quilometragem;
     private Integer diaria;
     private Integer almoco;
     private Integer criterioRevisita;
     private Set viagems = new HashSet(0);
     private Set jurisdicaos = new HashSet(0);

    public Rota() {
    }

	
    public Rota(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public Rota(Inspetoria inspetoria, String nome, Integer quilometragem, Integer diaria, Integer almoco, Integer criterioRevisita, Set viagems, Set jurisdicaos) {
       this.inspetoria = inspetoria;
       this.nome = nome;
       this.quilometragem = quilometragem;
       this.diaria = diaria;
       this.almoco = almoco;
       this.criterioRevisita = criterioRevisita;
       this.viagems = viagems;
       this.jurisdicaos = jurisdicaos;
    }
   
    public Long getIdrota() {
        return this.idrota;
    }
    
    public void setIdrota(Long idrota) {
        this.idrota = idrota;
    }
    public Inspetoria getInspetoria() {
        return this.inspetoria;
    }
    
    public void setInspetoria(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getQuilometragem() {
        return this.quilometragem;
    }
    
    public void setQuilometragem(Integer quilometragem) {
        this.quilometragem = quilometragem;
    }
    public Integer getDiaria() {
        return this.diaria;
    }
    
    public void setDiaria(Integer diaria) {
        this.diaria = diaria;
    }
    public Integer getAlmoco() {
        return this.almoco;
    }
    
    public void setAlmoco(Integer almoco) {
        this.almoco = almoco;
    }
    public Integer getCriterioRevisita() {
        return this.criterioRevisita;
    }
    
    public void setCriterioRevisita(Integer criterioRevisita) {
        this.criterioRevisita = criterioRevisita;
    }
    public Set getViagems() {
        return this.viagems;
    }
    
    public void setViagems(Set viagems) {
        this.viagems = viagems;
    }
    public Set getJurisdicaos() {
        return this.jurisdicaos;
    }
    
    public void setJurisdicaos(Set jurisdicaos) {
        this.jurisdicaos = jurisdicaos;
    }




}


