package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 19/03/2015 11:54:19 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Viagem generated by hbm2java
 */
public class Viagem implements java.io.Serializable {

    private Long idviagem;
    private Categoria categoria;
    private Fiscal fiscal;
    private Rota rota;
    private Date inicio;
    private Date fim;
    private String observacao;
    private Boolean gerouOrdem;

    public Viagem() {
    }

    public Viagem(Categoria categoria, Fiscal fiscal, Rota rota) {
        this.categoria = categoria;
        this.fiscal = fiscal;
        this.rota = rota;
    }

    public Viagem(Categoria categoria, Fiscal fiscal, Rota rota, Date inicio, Date fim, String observacao) {
        this.categoria = categoria;
        this.fiscal = fiscal;
        this.rota = rota;
        this.inicio = inicio;
        this.fim = fim;
        this.observacao = observacao;
    }

    public Long getIdviagem() {
        return this.idviagem;
    }

    public void setIdviagem(Long idviagem) {
        this.idviagem = idviagem;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Fiscal getFiscal() {
        return this.fiscal;
    }

    public void setFiscal(Fiscal fiscal) {
        this.fiscal = fiscal;
    }

    public Rota getRota() {
        return this.rota;
    }

    public void setRota(Rota rota) {
        this.rota = rota;
    }

    public Date getInicio() {
        return this.inicio;
    }

    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }

    public Date getFim() {
        return this.fim;
    }

    public void setFim(Date fim) {
        this.fim = fim;
    }

    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    public Boolean getGerouOrdem() {
        return gerouOrdem;
    }

    public void setGerouOrdem(Boolean gerouOrdem) {
        this.gerouOrdem = gerouOrdem;
    }

    
}
