package creago.dfisc.afg.sifis.planejamento.beans;
// Generated 20/02/2015 15:44:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Long idrole;
     private String description;
     private Set usuarios = new HashSet(0);

    public Role() {
    }

	
    public Role(String description) {
        this.description = description;
    }
    public Role(String description, Set usuarios) {
       this.description = description;
       this.usuarios = usuarios;
    }
   
    public Long getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Long idrole) {
        this.idrole = idrole;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


