package creago.dfisc.afg.sifis.security.entities;
// Generated 20/02/2015 15:44:23 by Hibernate Tools 4.3.1


import creago.dfisc.afg.sifis.planejamento.entities.Fiscal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long idusuario;
     private Fiscal fiscal;
     private String username;
     private String password;
     private String nome;
     private String sobrenome;
     private Integer matricula;
     private String email;
     private String avatar;
     private Set roles = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String username, String password, String nome, String sobrenome, Integer matricula, String email) {
        this.username = username;
        this.password = password;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.matricula = matricula;
        this.email = email;
    }
    public Usuario(Fiscal fiscal, String username, String password, String nome, String sobrenome, Integer matricula, String email, String avatar, Set roles) {
       this.fiscal = fiscal;
       this.username = username;
       this.password = password;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.matricula = matricula;
       this.email = email;
       this.avatar = avatar;
       this.roles = roles;
    }
   
    public Long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Long idusuario) {
        this.idusuario = idusuario;
    }
    public Fiscal getFiscal() {
        return this.fiscal;
    }
    
    public void setFiscal(Fiscal fiscal) {
        this.fiscal = fiscal;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


